amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 3.9
    laser_min_range: 0.0
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.1
    update_min_a: 0.5
    update_min_d: 0.2
    z_hit: 0.8
    z_max: 0.05
    z_rand: 0.15
    z_short: 0.05
    scan_topic: "/scan_filtered"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity: 0.0
    min_y_velocity: 0.0
    min_theta_velocity: 0.0
    max_x_velocity: 0.26
    max_y_velocity: 0.0
    max_theta_velocity: 1.0
    min_in_place_x_velocity: 0.0
    min_in_place_y_velocity: 0.0
    min_in_place_theta_velocity: 0.0
    max_in_place_x_velocity: 0.0
    max_in_place_y_velocity: 0.0
    max_in_place_theta_velocity: 1.0
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    decel_lim_theta: -3.2
    vx_samples: 20
    vy_samples: 5
    vtheta_samples: 20
    sim_time: 1.7
    xy_goal_tolerance: 0.25
    yaw_goal_tolerance: 0.25
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

recoveries_server:
  ros__parameters:
    use_sim_time: false
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

bt_navigator:
  ros__parameters:
    use_sim_time: false
    goal_blackboard_id: "goal"
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odometry/filtered"
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: "odom"
      robot_base_frame: "base_link"
      use_sim_time: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_link"
      use_sim_time: false
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ["planner_server", "controller_server", "recoveries_server", "bt_navigator", "waypoint_follower"]

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

explore:
  ros__parameters:
    use_sim_time: false
    planner_name: "planner_server"
    controller_name: "controller_server"
    goal_topic: "/explore/goal"
    map_topic: "/map"
    min_frontier_size: 0.5
    potential_field_scaling: 1.0
    orientation_penalty: 1.0
    exploring_action_name: "explore"
    robot_base_frame: "base_link"
    use_potential_field: true
    use_orientation_penalty: true
    use_conservative_approach: true
    timeout: 600.0
