x-ros-env: &ros-env
  DEV: ${DEV:-false}
  PYTHONUNBUFFERED: 1

services:
  ros2_frontend:
    image: nginx:alpine
    volumes:
      - ./src/web_server/frontend:/usr/share/nginx/html
      - ./src/web_server/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
    restart: unless-stopped

  ros2_lidar:
    build:
      context: .
      dockerfile: lidar.dockerfile
    volumes:
      - .:/ros2_ws/
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      <<: *ros-env
    network_mode: host
    ipc: host 
    privileged: true
    restart: unless-stopped

  ros2_diff_robot:
    build:
      context: .
      dockerfile: DiffDriveHardware.dockerfile
    volumes:
      - .:/ros2_ws/
    devices:
      - /dev/:/dev/
    environment:
      <<: *ros-env
      DIFF_DRIVE_TTY: ${DIFF_DRIVE_TTY:-/dev/ttyACM1}
      IMU_TTY: ${IMU_TTY:-/dev/ttyACM5}
      INA226_TTY: /dev/ttyACM2
    network_mode: host
    ipc: host 
    privileged: true
    restart: unless-stopped

  ros2_knife_controller:
    build:
      context: .
      dockerfile: KnifeMotorController.dockerfile
    volumes:
      - .:/ros2_ws/
    devices:
      - /dev/ttyACM4:/dev/ttyACM4
    environment:
      <<: *ros-env
    network_mode: host
    ipc: host 
    privileged: true
    restart: unless-stopped

  ros2_camera_rp:
    build:
      context: .
      dockerfile: CameraRp.dockerfile
    volumes:
      - .:/ros2_ws/
    devices:
      - /dev/:/dev/
    environment:
      <<: *ros-env
      ALWAYS_ON_APRILTAG: false
    network_mode: host
    ipc: host 
    privileged: true
    restart: unless-stopped


  ros2_nav2:
    build:
      context: .
      dockerfile: nav2.dockerfile
    ipc: host
    volumes:
      - .:/ros2_ws/
    devices:
      - /dev/:/dev/
    environment:
      <<: *ros-env
    network_mode: host
    privileged: true
    depends_on:
      - ros2_lidar
      - ros2_diff_robot
    restart: unless-stopped



  ros2_rosbridge:
    build:
      context: .
      dockerfile: Rosbridge.dockerfile
    ipc: host
    volumes:
      - .:/ros2_ws/
    environment:
      <<: *ros-env
      PYTHONDONTWRITEBYTECODE: 1
    network_mode: host
    restart: unless-stopped
