slam_toolbox:
  # Topics that slam_toolbox will subscribe to:
  ros__parameters:
    use_sim_time: false
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    odom_topic: "/odometry/filtered"
    map_update_interval: 0.1
    minimum_travel_distance: 0.05
    resolution: 0.01
    # use_scan_matching: false
    # use_scan_barycenter: false
    # Other necessary slam_toolbox parameters...

