slam_toolbox:
  # Topics that slam_toolbox will subscribe to:
  ros__parameters:
    use_sim_time: false
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    odom_topic: "/diff_drive_controller/odom"
    # Other necessary slam_toolbox parameters...

