version: '3'
services:
  ros2_robot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/ros2_ws/src
      - ./templates:/ros2_ws/templates
    devices:
      - /dev/ttyACM1:/dev/ttyACM1
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host  # This might be needed for ROS2 communication